#!/bin/bash
# bmks: unix bookmark management tool
#
# It takes an argument and an url, it can add, delete, list, and open through
# dmenu the list of bookmarks with a browser of choice.
#

URL_FILE_PATH=$HOME/.bmks/
URL_FILE_NAME=urls

DMENU_WIDTH=1366
DMENU_NUMBER_LINES=20

show_usage() {
	printf "bmks: unix bookmark management that sucks less

usage:
bmks dmenu
	manual switch for displaying bookmarks in dmenu

Dmenu will display a menu that will allow you to choose a bookmark and open it in your default browser."
}

bmks_display() {
	bmks_check
    grep -v '^#' "$URL_FILE_PATH/$URL_FILE_NAME" | sort |
		dmenu -l $DMENU_NUMBER_LINES -z $DMENU_WIDTH |
		awk -F ' - ' '{print $4}' |
		xargs -I '{}' "$BROWSER" {}
}

bmks_check() {
	[ ! -s "$URL_FILE_PATH/$URL_FILE_NAME" ] &&
		printf "Error: No bookmarks found to display. Try adding some!\n\n" && show_usage &&
		exit 0
}

[ ! -d "$URL_FILE_PATH" ] &&
	mkdir "$URL_FILE_PATH" [ ! -f "$URL_FILE_PATH/$URL_FILE_NAME" ] &&
	touch "$URL_FILE_PATH/$URL_FILE_NAME"

case "$1" in
	*) bmks_display ;;
esac
