#!/bin/bash
# bmks: unix bookmark management tool
#
# It takes an argument and an url, it can add, delete, list, and open through
# dmenu the list of bookmarks with a browser of choice.
#
# $1 command : help, add, del, ls, dmenu, fzf
# $2 string  : Url of choice

# set path where urls will be stored
URL_FILE_PATH=$HOME/.bmks/
# name of file urls will be stored in
URL_FILE_NAME=urls
# dmenu width
DMENU_WIDTH=1366
# dmenu number of lines
DMENU_NUMBER_LINES=20

show_usage() {
	printf "bmks: unix bookmark management that sucks less

usage:
bmks help
	show this help message
bmks add <url>
	add a new bookmark
bmks del
	remove a bookmark
bmks ls
	show all bookmarks
bmks dmenu
	manual switch for displaying bookmarks in dmenu
bmks fzf
	manual switch for displaying bookmarks in fzf

Dmenu will display a menu that will allow you to choose a bookmark and open it in your default browser."
}

bmks_add() {
	[ -z "$url" ] &&
		printf "Error: url must be provided\n\n" &&
		show_usage && exit 0
	printf "Name: "
	IFS= read -r name
	printf "Tags (comma-separated): "
	IFS= read -r tags
	[ -z "$name" ] &&
		name="$url"
	[ -z "$tags" ] &&
		echo "$name - $url" >> "$URL_FILE_PATH/$URL_FILE_NAME"
	[ -n "$tags" ] &&
		echo "$name - $url - [$tags]" >> "$URL_FILE_PATH/$URL_FILE_NAME"
}

bmks_ls() {
	bmks_check
	sort "$URL_FILE_PATH/$URL_FILE_NAME"
}

bmks_del() {
	bmks_check
	sed -i "/$(sort "$URL_FILE_PATH/$URL_FILE_NAME" |
		dmenu -l $DMENU_NUMBER_LINES -z $DMENU_WIDTH)/d" "$URL_FILE_PATH/$URL_FILE_NAME"
}

bmks_display() {
	bmks_check
	sort "$URL_FILE_PATH/$URL_FILE_NAME" |
		dmenu -l $DMENU_NUMBER_LINES -z $DMENU_WIDTH |
		awk -F ' - ' '{print $4}' |
		xargs -I '{}' "$BROWSER" {}
}

bmks_check() {
	[ ! -s "$URL_FILE_PATH/$URL_FILE_NAME" ] &&
		printf "Error: No bookmarks found to display. Try adding some!\n\n" && show_usage &&
		exit 0
}

[ ! -d "$URL_FILE_PATH" ] &&
	mkdir "$URL_FILE_PATH" [ ! -f "$URL_FILE_PATH/$URL_FILE_NAME" ] &&
	touch "$URL_FILE_PATH/$URL_FILE_NAME"

case "$1" in
	"help") show_usage ;;
	"add") url=$2; bmks_add ;;
	"del") bmks_del ;;
	"ls") bmks_ls ;;
	*) bmks_display ;;
esac
