#! /bin/sh
# prompt_yn: dmenu binary prompt script
#
# Gives dmenu propt labeled with $1 to perform command $2
#
# $1 Command: Yes, No
#
# Examples:
# './prompt "Do you want to shutdown?"' "shutdown -h now"'

[ "$( printf "No\nYes" | dmenu -i -p "$1")" \
    = "Yes" ] && $2
